# 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣
例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

In [2]:
#載入圖片
import cv2
img_path = 'C:/Users/user/Desktop/Python/computer_vision/D1/Part01/lena.png'

In [3]:
# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

In [4]:
type(img)

numpy.ndarray

In [5]:
print(img)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ..., 
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ..., 
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ..., 
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ..., 
 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ..., 
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ..., 
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ..., 
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [6]:
cv2.imshow('bgr', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# 把 RGB 3 個維度拆開
blue = img[:, :, 0]
green = img[:, :, 1]
red = img[:, :, 2]

In [8]:
# 為了要不斷顯示圖片，所以使用一個迴圈
while True:
    # 顯示彩圖
    cv2.imshow('bgr', img)
    # 顯示灰圖
    cv2.imshow('b', blue)
    cv2.imshow('g', green)
    cv2.imshow('r', red)

    # 直到按下 ESC 鍵才會自動關閉視窗結束程式
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break